### ISSUE TITLE
Unable to start 

### ISSUE THREAD

**Issue by lemkova** [TJRoger/node-dota2-spectator#1]
Hi , i was trying to run this on my vps but it gave me error.

i have done this step
1. `git clone` this repos
2. npm install at the cloned directory
3. change config.js to my bot info
4. `node example` but gave me error

/home/steam/newbot/node-dota2-spectator/index.js:37
var schema = Dota2 = builder.build();
                            ^
TypeError: Cannot read property 'build' of null
    at Object.<anonymous> (/home/steam/newbot/node-dota2-spectator/index.js:37:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/steam/newbot/node-dota2-spectator/example.js:14:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

did i do it wrong?

**Comment by TJRoger** [comment]
seem something wrong with your resource files. You can download the resource files from [here](https://github.com/SteamRE/SteamKit/tree/master/).

**Comment by TJRoger** [comment]
@graceda I have updated the repo and added resources file. You can update your git using `git pull` to get the files now.

**Comment by mnickkk** [comment]
The problem is you're requesting files from **protobufs** folder in index.js, but there is no such directory. Windows sees no difference between **protobufs** and **Protobufs**, whereas UNIX systems do care about the letter size.

**Comment by TJRoger** [comment]
@mnickkk Yes, you are right. The folder in my local repo is `protobufs`, but when pushed to github, it becomes `Protobufs`.

**Comment by TJRoger** [comment]
@mnickkk It must be the cache of git causing the problem. I have fixed it.

**Comment by lemkova** [comment]
i dont know what wrong with this, after i re clone this repo and re install the npm, it gave me another error

/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:723
             throw Error("Unexpected token at line "+this.tn.line+": "+token);
                                                                      ^
Error: Unexpected token at line 1: {
    at Error (native)
    at ProtoBuf.DotProto.ParserPrototype.parse (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:723:82)
    at ProtoBuf.Builder.BuilderPrototype.import (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:4757:88)
    at ProtoBuf.Builder.BuilderPrototype.import (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:4757:43)
    at Object.ProtoBuf.loadJson (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:5270:26)
    at Object.ProtoBuf.loadProto (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:5173:25)
    at Object.ProtoBuf.loadProtoFile (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js:5219:52)
    at Object.<anonymous> (/home/steam/wewbot/node-dota2-spectator/index.js:34:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by TJRoger** [comment]
@graceda  try it now again. Something wrong with the old resources files.

**Comment by lemkova** [comment]
@TJRoger

7 Aug 11:23:14 - Bot is trying to connect to steam network...
7 Aug 11:23:14 - Connected to steam network.
7 Aug 11:23:14 - Bot is trying to login...
/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs/dist/ProtoBuf.js                :2949
    clone[i] = cloneRaw(value, binaryAsBase64, longsAsStrings, field.type, fie
                                                                    ^
TypeError: Cannot read property 'type' of undefined
    at cloneRaw (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs                /dist/ProtoBuf.js:2949:97)
    at cloneRaw (/home/steam/wewbot/node-dota2-spectator/node_modules/protobufjs                /dist/ProtoBuf.js:2949:44)
    at MessagePrototype.toRaw (/home/steam/wewbot/node-dota2-spectator/node_modu                les/protobufjs/dist/ProtoBuf.js:2964:28)
    at Object.Steam._processProto (/home/steam/wewbot/node-dota2-spectator/node_                modules/steam/lib/steam_client.js:20:17)
    at SteamClient._netMsgReceived (/home/steam/wewbot/node-dota2-spectator/node                _modules/steam/lib/steam_client.js:150:26)
    at SteamClient.handlers.(anonymous function) (/home/steam/wewbot/node-dota2-                spectator/node_modules/steam/lib/steam_client.js:269:10)
    at SteamClient._netMsgReceived (/home/steam/wewbot/node-dota2-spectator/node                _modules/steam/lib/steam_client.js:167:26)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (/home/steam/wewbot/node-dota2-spectator/node_modu                les/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:104:17)

bot was logged into steam, i got an auth-code on my email, i entered the auth-code, but still failed to start and gave me error as above.

**Comment by TJRoger** [comment]
@graceda It shows you failed to login. I can not see anything related to the spectator. It works fine on my mac , as I tested it right now.

**Comment by mnickkk** [comment]
@graceda this issue is explained here: https://github.com/seishun/node-steam/issues/222
To make node-dota2-spectator work you need to:
1) clone the repo
2) remove node-steam from the dependency list
3) npm install steam
4) npm install

**Comment by TJRoger** [comment]
@mnickkk Excellent! It is really the situation. I found out that the `peerDependency` seems not supported by npm 3+, so I added it to the dependency. Thanks a lot, I will update the repo and the install guide!

**Comment by lemkova** [comment]
@mnickkk great, it all worked well right now. thanks a lot guys.
